productionapp/GuestService/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView


urlpatterns = [
    path("home", views.HomePageView.as_view(), name="home"),
    path("",  views.HomePageView.as_view(), name=""),
    path("todo", views.list_todo, name="todo"),
    path("create_item", views.CreateItem.as_view(), name="create_item"),
    path("todo/<pk>/date", views.UpdateItem.as_view(), name="update_item"),
    path('todo/<id>/delete', views.delete_task, name='delete_task'),
    path("days", views.list_days, name="days"),
    path("create_day", views.CreateDay.as_view(), name="create_day"),
    path("create_att", views.CreateAtt.as_view(), name="create_att"),
    path('attractions/<id>/', views.details, name='details'),
    path("attractions", views.list_att, name="attractions"),
    path('att/<pk>/update', views.UpdateAtt.as_view(), name="update_att"),
    path('att/<id>/delete', views.delete_post, name='delete_att'),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

productionapp/productionapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),    
    path("", include("GuestService.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

productionapp/GuestService/models.py
# Create your models here.
import datetime
from django.utils import timezone
from django.db import models
from django.urls import reverse


class Days(models.Model):
    DATE_CHOICES = (("Day 1", '13. 2. 2023'),

                    ("Day 2", '14. 2. 2023'),

                    ('Day 3', '15. 2. 2023'),

                    ('Day 4', '16. 2. 2023'),

                    ('Day 5', '17. 2. 2023'),

                    ('Day 6', '18. 2. 2023')
                    )

    day_name = models.CharField(
        max_length=25, choices=DATE_CHOICES, unique=True)

    def get_absolute_url(self):
        return "/days"

    def __str__(self) -> str:
        return self.day_name


class Attractions(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=2000, default='', blank=True)
    image = models.ImageField(
        upload_to='GuestService/static',  default='', blank=True)
    day = models.ForeignKey(Days, on_delete=models.CASCADE)
    stop_number = models.PositiveIntegerField(default=0)
    image_of_us = models.ImageField(
        upload_to='GuestService/static', default='', blank=True)
    experience = models.CharField(max_length=2000, default='', blank=True)

    def __str__(self) -> str:
        return (self.name + '-' + self.stop_number + '-' + self.day.day_name)

    def get_absolute_url(self):
        return "/attractions"


def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)


class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    done = models.BooleanField(default=False)

    def get_absolute_url(self):
        return "/todo"

    def __str__(self):
        return f"{self.title}, {self.due_date}, {self.done}"

productionapp/GuestService/forms.py
from django import forms
from django.forms import ModelForm
from .models import Attractions, Days, ToDoItem


class DateInput(forms.DateInput):
    input_type = 'date'


class AttForm(ModelForm):
    class Meta:
        model = Attractions
        fields = "__all__"

class DayForm(ModelForm):
    class Meta:
        model = Days
        fields = "__all__"

class ItemForm(ModelForm):
    class Meta:
        model = ToDoItem
        fields = "__all__"

productionapp/GuestService/views.py
# pages/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from .models import Attractions, Days, ToDoItem
from .forms import AttForm, DayForm, ItemForm
from django.contrib import messages
from django.urls import reverse



class HomePageView(TemplateView):
    template_name = "home.html"

class CreateAtt(CreateView):
    model = Attractions
    form_class = AttForm
    template_name = "create_att.html"

def list_att(request):
  all_attractions = Attractions.objects.all()
  context = {"attractions" : all_attractions}
  return render(request, 'attractions.html', context)

class UpdateAtt(UpdateView):
  model = Attractions
  form_class = AttForm
  template_name = "update_att.html"


def delete_post(request, id):
    att = get_object_or_404(Attractions, pk=id)
    context = {'attraction': att}    
    
    if request.method == 'GET':
        return render(request, 'delete_att.html',context)
    elif request.method == 'POST':
        att.delete()
        messages.success(request,  'The post has been deleted successfully.')
        return redirect('/attractions')


def details(request, id):
  attraction = get_object_or_404(Attractions, pk=id)
  context = {"attractions" : attraction, "pk" : id, "image": attraction.image, "image_of_us": attraction.image_of_us, "description": attraction.description
  , "experience":attraction.experience}
  return render(request, 'details.html', context)

def list_days(request):
  all_days = Days.objects.all()
  context = {"days" : all_days}
  return render(request, 'days.html', context)

class CreateDay(CreateView):
    model = Days
    form_class = DayForm
    template_name = "create_day.html"

def list_todo(request):
  all_days = ToDoItem.objects.all()
  context = {"to_do" : all_days}
  return render(request, 'todo_list.html', context)    

def delete_task(request, id):
    att = get_object_or_404(ToDoItem, pk=id)
    context = {'item': att}    
    
    if request.method == 'GET':
        return render(request, 'delete_item.html',context)
    elif request.method == 'POST':
        att.delete()
        messages.success(request,  'The post has been deleted successfully.')
        return redirect('/todo')

class CreateItem(CreateView):
    model = ToDoItem
    form_class = ItemForm
    template_name = "create_item.html"

class UpdateItem(UpdateView):
    model = ToDoItem
    form_class = ItemForm
    template_name = "update_item.html"

productionapp/GuestService/templates/attractions.html
{% extends 'base.html' %} {% load static %} {% block content %}
<table style="overflow: auto; width: 90%">
<header>
  <tr>
    <th><b>Místo</b></th>
    <th><b>Popis</b></th>
    <th><b>Datum</b></th>
    <th></th>
    <th></th>
  </tr>
</header>
<tbody>
  {% for item in attractions %}
  <tr>
    <td><a href = "{% url 'details' item.id %}"><b>{{ item.name }}</b></a></td>

    <td>{{ item.description }}</td>
    <td>{{ item.day }}</td>
    <td><a href = "{% url 'update_att' item.id %}" >Edit</a></td>
    <td><a href =  "{% url 'delete_att' item.id %}" >Delete</a></td>
  </tr>
  {% endfor %}
</tbody>
</table>
</br>
<a href="{% url 'create_att' %}" class = 'add_att'
style="width: 90%; padding: 4px; display: inherit; text-align: center; 
border-radius: 15px; text-decoration: none; color: i
nherit; background-color: rgb(250, 250, 198, 0.9);">➕</a>
{% endblock %}

productionapp/GuestService/templates/base.html
{% load static %}

<head>
    <meta charset="utf-8">
    <link rel="icon" type="image/x-icon" href="{% static '/favicon (1).ico' %}">
    <title>
      Copenhagen
    </title>
  
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Dongle:wght@300&family=Poppins:wght@300&display=swap" rel="stylesheet">
  
    <!-- CSS Styles -->
    <link rel="stylesheet" type="text/css" href="{% static '/styles.css' %}">
  
    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/7a2c79c7cd.js" crossorigin="anonymous"></script>
  
  
  </head>

    <section id="title">
      <div class="container-fluid">
  
        <!-- Nav Bar -->
        <nav class="navbar navbar-expand-lg navbar-dark">
          <a class="navbar-brand" href="home"><h2>Copenhagen Trip 02/2023</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto ">
              <li class="nav-item">
                <a class="nav-link" href="home"><h2>Home</h2></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="days"><h2>Itinerary</h2></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/attractions"><h2>Attractions List</h2></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="todo"><h2>To Do List</h2></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=""><h2>About Copenhagen</h2></a>
              </li>
  
            </ul>
  
          </div>
        </nav>
  
      </section>
  <section id = 'varies'>

    {% block content %} 
    {% endblock %}

  </section>

productionapp/GuestService/templates/create_att.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h2><b>Create New Attraction</b></h2>
<form action="" method="POST" enctype="multipart/form-data"  class = 'form'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" class="button" />

</form>
{% endblock %}

productionapp/GuestService/templates/create_day.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h2><b>Add Day</b></h2>
<form action="" method="POST" class = 'form'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" class="button" />

</form>
{% endblock %}

productionapp/GuestService/templates/create_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h2><b>Create New Task</b></h2>
<form action="" method="POST" class = 'form'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" class="button" />

</form>
{% endblock %}

productionapp/GuestService/templates/days.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
  <div>
    <table class = 'line_table'>
      <thead>
        <tr>
          <th   style = "font-weight: bold;
          font-size: 18px;">Den</th>
          <th>Zastávky</th>
        </tr>
      </thead>
      <tbody>
      {% for day in days %}
        <tr>
          <td>
          <b>{{ day.day_name }}</b>
          </td>
          <td><ul>
                {% for stop in day.attractions_set.all %}
                <a href = "{% url 'details' stop.id %}">
                    <li>{{ stop.stop_number }}</li>
                  <div >{{ stop.name }}</div>
              </a>  {% endfor %}
            </ul>
          </td>
          {% endfor %}

        </tr>
      </tbody>
    </table>
  </div>

</br>
<a href="{% url 'create_day' %}" class = 'add_day'
style="width: 90%; padding: 4px; display: inherit; text-align: center; 
border-radius: 15px; text-decoration: none; color: i
nherit; background-color: rgb(250, 250, 198, 0.9);">➕</a>

{% endblock %}

productionapp/GuestService/templates/delete_att.html
{% extends 'base.html' %} 

{% load static %} 

{% block content %}
<h2><b>Delete Attraction</b></h2>
<form method="post"  class = 'form'>
  {% csrf_token %} 
  <p>Are you sure you want to delete {{ attraction.name }}?</p>
  <input type="submit" value="Confirm" class="button" />

</form>
{% endblock %}

productionapp/GuestService/templates/delete_item.html
{% extends 'base.html' %} 

{% load static %} 

{% block content %}
<h2><b>Delete Attraction</b></h2>
<form method="post"  class = 'form'>
  {% csrf_token %} 
  <p>Are you sure you want to delete {{ to_do.title }}?</p>
  <input type="submit" value="Confirm" class="button" />

</form>
{% endblock %}

productionapp/GuestService/templates/details.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<a href = "{% url 'attractions' %}">
<button class="button">Go back</button></br></br>
</a>

<h1>This is <b>{{ attractions.name }}</b>!</h1>

<h3>This is the picture we found:</h3>
<img src="/{{ attractions.image }}" /> </br></br></br></br>

<h3>And this is us... 😌</h3> </br>
<img src="/{{ attractions.image_of_us }}" /></br></br></br></br>

<h3>And this is what we thought about it:</h3>
{{ attractions.experience }}


{% endblock %}

productionapp/GuestService/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <section>

    <div class="map">

      <div class="col-lg-12">
        <div class="container-fluid map-con">

          <iframe id='map' src="https://www.google.com/maps/d/embed?mid=1kj5k8t29wCGjNfZa7CXwNHnct_ZLY5Cz&ehbc=2E312F" width="640" height="480"></iframe>
        </div>
      </div>
    </div>

  </section>
  {% endblock %}

productionapp/GuestService/templates/todo_list.html
{% extends 'base.html' %} 

{% load static %} 

{% block content %}
<table style="overflow: auto; width: 90%">
<header>
  <tr>
    <th><b>Úkol</b></th>
    <th><b>Stav</b></th>
    <th><b>Deadline</b></th>
    <th></th>
    <th></th>
  </tr>
</header>
<tbody>
{% for item in to_do %}

<tr>
    <td><a href = "{% url 'update_item' item.id %}">{% if item.done is False %}<b>{{ item.title }}</b></a></td>
    {% else %} 
    <s>{{ item.title }}</s></a></td>
    {% endif %}
    <td><b>{% if item.done is False %}} No {% else %} Yes {% endif %}</b></td>
    <td><b>{{ item.due_date }}</b></td>
    <td><a href = "{% url 'update_item' item.id %}" >Edit</a></td>
    <td><a href =  "{% url 'delete_task' item.id %}" >Delete</a></td>
  </tr>
  {% endfor %}
</tbody>
</table>
</br>
<a href="{% url 'create_item' %}" class = 'add_att'
style="width: 90%; padding: 4px; display: inherit; text-align: center; 
border-radius: 15px; text-decoration: none; color: i
nherit; background-color: rgb(250, 250, 198, 0.9);">➕</a>
{% endblock %}

productionapp/GuestService/templates/update_att.html
{% extends 'base.html' %} 

{% load static %} 

{% block content %}
<h2><b>Update Attraction</b></h2>
<form method="post" class = 'form'>
  {% csrf_token %} 
  {{ form.as_p}}</br>
  <input type="submit" value="Update" class="button" />
</form>
{% endblock %}

productionapp/GuestService/templates/update_item.html
{% extends 'base.html' %} 

{% load static %} 

{% block content %}
<h2><b>Update Attraction</b></h2>
<form method="post" class = 'form'>
  {% csrf_token %} 
  {{ form.as_p}}</br>
  <input type="submit" value="Update" class="button" />
</form>
{% endblock %}